### ISSUE TITLE
Development and contribution workflow

### ISSUE THREAD

**Issue by sagarnasit** [rtCamp/amp-admanager#64]
Workflow:
- Every PR needs to be merged to develop branch first.
- Need to test on develop
- If the test goes good and QA approves then only create a PR against master.
- Need to plan a release with changelog.
- **No PR will go to master directly**

@sagarnasit 

- [x] Update Readme with the descriptive workflow
- [x] update section for the contributors (steps as this repo is public)

@DevikVekariya 

- [x] Make the master branch protected
- [x] Add rule for the PRs, to get minimum 1 approval to merge.

**Comment by DevikVekariya** [comment]
Workflow pushed to develop.
WIll release to master in next release
