### ISSUE TITLE
Add phpcs pipeline to the project

### ISSUE THREAD

**Issue by DevikVekariya** [rtCamp/amp-admanager#66]
Add pipeline with needful phpcs checks

- [x] Add needful tokens => @DevikVekariya 
- [x] Configure GH actions for the phpcs checks => @kiranpotphode 

Seems necessary from this => https://github.com/rtCamp/amp-admanager/pull/63#discussion_r371226718

**Comment by thrijith** [comment]
@DevikVekariya @kiranpotphode The project needs a PHPCS ruleset as well, apart from the workflow, for exclusion of test files from PHPCS checking.

**Comment by kiranpotphode** [comment]
@DevikVekariya PHPCS GH action is already configured. Added the phpcs.xml file and excluded the tests folder from the scan

**Comment by kiranpotphode** [comment]
PR for this
https://github.com/rtCamp/amp-admanager/pull/67

**Comment by kiranpotphode** [comment]
@DevikVekariya This issue can be closed.
